name: Fern Generate
on:
  push:
    branches:
      - main

jobs:
  fern-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Fern
        run: npm install -g fern-api

      - name: Generate docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate --docs